name: build
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - uses: actions/checkout@v1
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -count=1 ./...

    - name: Upload coverage to Codecov

      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
